title: Welcome to Seongmin's web site
author: Seongmin Kim
url: https://seongminkim-0215.github.io/ # root address of the site
description: > # description of the site (multiple lines allowed)
  Hi, I’m Seongmin Kim. I’m currently a postdoctoral researcher in Chemical and Biological Engineering at Seoul National University, where I work on AI-driven approaches for inorganic materials synthesizability and synthesis planning.
  I earned my Ph.D. in Chemical and Biomolecular Engineering from KAIST (2021–2025), following my M.S. in Chemical and Biological Engineering from Seoul National University (2018–2020) and my B.S. in Chemical Engineering from POSTECH (2012–2018).
  My research focuses on developing machine-learning and large-language-model–based tools that help design synthesizable materials and predict practical experimental methods.

permalink: /:slug

favicon: "./logo.png" # relative path to site's favicon

#theme: moonwalk # if you are using GitHub Pages, change it to remote_theme: abhinavs/moonwalk
#remote_theme: abhinavs/moonwalk

theme_config:
  appearance: "dark"
  appearance_toggle: true
  back_home_text: "home.."
  date_format: "%Y-%m"
  show_description: true
  show_navbar: true
  show_footer: true
  show_copyright: true

  show_projects: false
  show_blog: true
  show_old_projects: false
  show_misc_list: true
  show_misc_list2: true

  home:
    title_blog: Selected Publications
    title_misc_list: Research Experiences
    title_misc_list2: Educations
    title_footer: Related Sites



soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

highlighter: rouge

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
